# Generated by Django 4.2 on 2024-03-18 17:02

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('Category_id', models.AutoField(db_column='CategoryID', primary_key=True, serialize=False)),
                ('Name', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('TagID', models.AutoField(db_column='TagID', primary_key=True, serialize=False)),
                ('Name', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(db_column='UserID', primary_key=True, serialize=False)),
                ('username', models.TextField()),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.RenameField(
            model_name='card',
            old_name='adds',
            new_name='Favorites',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='views',
            new_name='Views',
        ),
        migrations.RemoveField(
            model_name='card',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='card',
            name='id',
        ),
        migrations.RemoveField(
            model_name='card',
            name='question',
        ),
        migrations.RemoveField(
            model_name='card',
            name='upload_date',
        ),
        migrations.AddField(
            model_name='card',
            name='CardID',
            field=models.AutoField(db_column='CardID', default=django.utils.timezone.now, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='UploadDate',
            field=models.DateTimeField(auto_now_add=True, db_column='UploadDate', default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='card',
            name='tags',
        ),
        migrations.CreateModel(
            name='CardTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(db_column='CardID', on_delete=django.db.models.deletion.CASCADE, to='cards.card')),
                ('tag', models.ForeignKey(db_column='TagID', on_delete=django.db.models.deletion.CASCADE, to='cards.tag')),
            ],
            options={
                'db_table': 'CardTags',
            },
        ),
        migrations.AddField(
            model_name='card',
            name='Answer',
            field=models.TextField(default=datetime.datetime(2024, 3, 18, 20, 1, 5, 161540)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='CategoryID',
            field=models.ForeignKey(db_column='CategoryID', default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='cards.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='Question',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='tags',
            field=models.ManyToManyField(related_name='cards', through='cards.CardTags', to='cards.tag'),
        ),
        migrations.AddConstraint(
            model_name='cardtags',
            constraint=models.UniqueConstraint(fields=('card', 'tag'), name='unique_card_tag'),
        ),
    ]
