# Generated by Django 4.2 on 2024-03-18 21:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_alter_card_uploaddate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='cardtags',
            name='unique_card_tag',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='CategoryID',
            new_name='Category',
        ),
        migrations.RemoveField(
            model_name='card',
            name='CardID',
        ),
        migrations.AddField(
            model_name='card',
            name='card_id',
            field=models.AutoField(db_column='CardID', default=datetime.datetime(2024, 3, 18, 21, 8, 29, 10226, tzinfo=datetime.timezone.utc), primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='Answer',
            field=models.TextField(db_column='Answer'),
        ),
        migrations.AlterField(
            model_name='card',
            name='Favorites',
            field=models.IntegerField(db_column='Favorites', default=0),
        ),
        migrations.AlterField(
            model_name='card',
            name='Question',
            field=models.TextField(db_column='Question'),
        ),
        migrations.AlterField(
            model_name='card',
            name='UploadDate',
            field=models.DateTimeField(auto_now_add=True, db_column='UploadDate'),
        ),
        migrations.AlterField(
            model_name='card',
            name='Views',
            field=models.IntegerField(db_column='Views', default=0),
        ),
        migrations.AlterField(
            model_name='card',
            name='tags',
            field=models.ManyToManyField(related_name='Cards', through='cards.CardTags', to='cards.tag'),
        ),
        migrations.AlterField(
            model_name='category',
            name='Name',
            field=models.TextField(db_column='Name', unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='Name',
            field=models.TextField(db_column='Name', unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.TextField(db_column='UserName'),
        ),
    ]
