# Generated by Django 4.2 on 2024-03-25 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_card_check_status'),
    ]

    operations = [
    ]
