# Generated by Django 4.2 on 2024-04-15 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0009_add_id_field_to_cardtags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardtags',
            options={'managed': False},
        ),
        migrations.AddField(
            model_name='card',
            name='author',
            field=models.ForeignKey(db_column='AuthorID', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
